wandb_version: 1

Delay:
  desc: null
  value: 2
History:
  desc: null
  value: 5
Scheduler:
  desc: null
  value: 'NO'
Time_resolution:
  desc: null
  value: 1 days 00:00:00
_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: huggingface
    huggingface_version: 4.21.3
    is_jupyter_run: true
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: Loss on train
      5: 1
      6:
      - 1
    - 1: Loss on test
      5: 1
      6:
      - 1
    - 1: Electron Density correlation (R)
      5: 1
      6:
      - 1
    - 1: Proton Density correlation (R)
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    python_version: 3.10.6
    start_time: 1673176108.961222
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      3:
      - 2
      - 7
      - 13
      - 16
      - 23
      4: 3.10.6
      5: 0.13.7
      6: 4.21.3
      8:
      - 1
      - 5
drop:
  desc: null
  value: 0.3
epochs:
  desc: null
  value: 60
firstConv:
  desc: null
  value: 8
kernel:
  desc: null
  value:
  - 3
  - 3
lr:
  desc: null
  value: 1.0e-05
secondConv:
  desc: null
  value: 16
thirdConv:
  desc: null
  value: 32
wd:
  desc: null
  value: 0.1
